---
title: "Week 1"
format: html
---

### Basic Math Operations

| Operator | Operation                         |
|----------|-----------------------------------|
| `+`      | Add                               |
| `-`      | Subtract                          |
| `*`      | Multiply                          |
| `/`      | Divide                            |
| `//`     | Integer Division (`3 // 2 = 1`)   |
| `%`      | Modulus (remainder) (`7 % 2 = 1`) |
| `**`     | Exponentiaton (`3**2` = $3^2$)    |
| `()`     | Order of operations               |

: Python Math Operators

`#` = comment character

```{python}
# 3 ** 2
7 % 2
```

### Functions

`round()`

```{python}

round(1.99)
```

`abs()`

```{python}
abs(-10)
```

`max()`

```{python}
max(2, -10, 40)
```

### Variables

Use `=` to assign values to variables

NB cannot use hyphens in naming variables.... `my-name = 1` Error (tries to subtract `name` from `my`). `my_name = 1` Correct assignment.

Cannot use

`.`

`^`

`!`

`$`

\@

`+`

`-`

`/`

`(`

`{`

### Packages

Python download at <https://www.python.org>

You get:

-   Python interpreter

-   Functions, variables, and classes

-   Python standard library

Modules \> Packages

Python Packaage Index [PyPI](https://pypi.org)

### Installing Packages

`pip`Remember this is a command-line tool, not python

### Importing Packages

```{python}
import numpy as np
```

```{python}
np.sqrt(35)
```

### Namespacing

Have to use namespacing `<package>.<function>`

```{python}
np.ceil(3.2)
```

Use an **alias**, that is `import numpy as np`

NB: `help()` will show all components of package...this is VERY COOL

```{python}
import math
help(math)
```

Also, help for specific functions

```{python}
help(math.sqrt)
```

Check out

-   [Python Packaging User Guide](https://packaging.python.org/en/latest/)

-   [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

### Functions

NB: `round()` is a built-in python function. Complete list of built-ins at <https://docs.python.org/3/library/functions.html>

```{python}
round(1.732051, ndigits = 2)
```

Argument Names: Find using `help()`

**MUST BE NAMESPACED**

```{python}
help(round)
```

```{python}
help(math.sqrt)
```

```{python}
help(round)
```

`pd.value_counts()` will count number of occurrences in a vector...or rather array

```{python}
import pandas as pd
```

```{python}
help(pd.value_counts)
```